# PagesCMS Configuration for Hope and Despair
# Matches the actual content schema used in the project

# Media Configuration
media:
  input: public/images
  output: /images

# Content Collections
content:
  # Hope Articles
  - name: hope
    label: Hope Stories
    type: collection
    path: src/content/hope
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: id
        label: ID
        type: number
        
      - name: title
        label: Title
        type: string
        required: true
        
      - name: summary
        label: Summary
        type: text
        required: true
        
      - name: date
        label: Date
        type: date
        required: true
        
      - name: source
        label: Source
        type: string
        
      - name: sourceUrl
        label: Source URL
        type: string
        
      - name: sourceLinkTitle
        label: Source Link Title
        type: string
        
      - name: sourceLinkDescription
        label: Source Link Description
        type: text
        
      - name: timeAgo
        label: Time Ago
        type: string
        
      - name: category
        label: Category
        type: string
        default: hope
        
      - name: tags
        label: Tags
        type: string
        list: true
        
      - name: url
        label: URL
        type: string
        
      - name: body
        label: Content
        type: rich-text

  # Despair Articles
  - name: despair
    label: Despair Stories
    type: collection
    path: src/content/despair
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: id
        label: ID
        type: number
        
      - name: title
        label: Title
        type: string
        required: true
        
      - name: summary
        label: Summary
        type: text
        required: true
        
      - name: date
        label: Date
        type: date
        required: true
        
      - name: source
        label: Source
        type: string
        
      - name: sourceUrl
        label: Source URL
        type: string
        
      - name: sourceLinkTitle
        label: Source Link Title
        type: string
        
      - name: sourceLinkDescription
        label: Source Link Description
        type: text
        
      - name: timeAgo
        label: Time Ago
        type: string
        
      - name: category
        label: Category
        type: string
        default: despair
        
      - name: tags
        label: Tags
        type: string
        list: true
        
      - name: url
        label: URL
        type: string
        
      - name: body
        label: Content
        type: rich-text

  # Context Articles
  - name: context
    label: Context Stories
    type: collection
    path: src/content/context
    format: yaml-frontmatter
    filename: "{slug}.md"
    fields:
      - name: id
        label: ID
        type: number
        
      - name: title
        label: Title
        type: string
        required: true
        
      - name: summary
        label: Summary
        type: text
        required: true
        
      - name: date
        label: Date
        type: date
        required: true
        
      - name: source
        label: Source
        type: string
        
      - name: sourceUrl
        label: Source URL
        type: string
        
      - name: sourceLinkTitle
        label: Source Link Title
        type: string
        
      - name: sourceLinkDescription
        label: Source Link Description
        type: text
        
      - name: timeAgo
        label: Time Ago
        type: string
        
      - name: category
        label: Category
        type: string
        default: context
        
      - name: tags
        label: Tags
        type: string
        list: true
        
      - name: url
        label: URL
        type: string
        
      - name: body
        label: Content
        type: rich-text