title: "Hope and Despair"
description: "Mapping the emotional landscape of our times through stories of progress and setback"
url: "https://hopeanddespair.world"
author: "Hope and Despair Team"
social:
  twitter: ""
  github: ""
  email: ""
analytics:
  googleAnalyticsId: ""
  umamiAnalyticsId: ""
seo:
  ogImage: ""
  keywords:
    - hope
    - despair
    - context
    - news
    - analysis
    - progress
    - setback
    - world events